"""Search query normalization utilities."""

from __future__ import annotations

_STOP_WORDS: frozenset[str] = frozenset(
    {
        "a",
        "an",
        "the",
        "this",
        "that",
        "these",
        "those",
        "some",
        "any",
        "each",
        "every",
        "both",
        "all",
        "few",
        "more",
        "most",
        "other",
        "such",
        "in",
        "on",
        "at",
        "by",
        "for",
        "with",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "from",
        "to",
        "of",
        "as",
        "up",
        "down",
        "off",
        "out",
        "over",
        "under",
        "and",
        "or",
        "but",
        "nor",
        "so",
        "yet",
        "either",
        "neither",
        "i",
        "me",
        "my",
        "we",
        "us",
        "our",
        "you",
        "your",
        "he",
        "him",
        "his",
        "she",
        "her",
        "it",
        "its",
        "they",
        "them",
        "their",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "can",
        "shall",
        "get",
        "got",
        "go",
        "going",
        "come",
        "came",
        "make",
        "made",
        "say",
        "said",
        "know",
        "think",
        "see",
        "look",
        "not",
        "no",
        "nor",
        "just",
        "also",
        "too",
        "very",
        "really",
        "quite",
        "much",
        "many",
        "how",
        "why",
        "what",
        "when",
        "where",
        "which",
        "who",
        "there",
        "here",
        "then",
        "than",
        "never",
        "always",
        "often",
        "still",
        "now",
        "today",
        "help",
        "want",
        "need",
        "wish",
        "try",
        "using",
        "used",
        "like",
        "new",
        "old",
        "good",
        "bad",
        "best",
        "worst",
    }
)


def query_keywords(query: str, min_length: int = 5) -> frozenset[str]:
    """Non-stop words from query at or above min_length chars, lowercase.

    Used for result relevance gating — short generic words (e.g. "home", "data")
    match too broadly to be useful as overlap signals.
    """
    return frozenset(
        w.lower() for w in query.split() if len(w) >= min_length and w.lower() not in _STOP_WORDS
    )


def normalize_search_query(query: str, max_terms: int = 4) -> str:
    """Strip stop words and cap to max_terms. Returns query unchanged if already short."""
    words = query.split()
    if len(words) <= max_terms:
        return query

    key_terms = [w for w in words if w.lower() not in _STOP_WORDS and len(w) > 2]
    if not key_terms:
        return " ".join(words[:max_terms])

    return " ".join(key_terms[:max_terms])
